load("Cit_par.m")

C_1a = [ (Cybdot-2*mub)*b/V 0              0                  0                  ;...
        0                  -0.5*b/V       0                  0                  ;...
        0                  0              -2*mub*KX2*b^2/V^2 2*mub*KXZ*b^2/V^2  ;...
        Cnbdot*b/V         0              2*mub*KXZ*b^2/V^2  -2*mub*KZ2*b^2/V^2 ];

C_2a = [ Cyb CL Cyp*b/(2*V) (Cyr-4*mub)*b/(2*V) ;...
        0   0  b/(2*V)     0                   ;...
        Clb 0  Clp*b/(2*V) Clr*b/(2*V)         ;...
        Cnb 0  Cnp*b/(2*V) Cnr*b/(2*V)         ];

C_3a = [ Cyda Cydr ;...
        0    0    ;...
        Clda Cldr ;...
        Cnda Cndr ];

Aa = -1*inv(C_1)*C_2;
Ba = -1*inv(C_1)*C_3;
